name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Latest Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Python Dependencies
        run: pip install -r requirements/nox-deps.txt
      - name: Run Tests
        run: nox -t test

  environments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: pip install -r requirements/nox-deps.txt
      - name: Run Tests
        run: nox -t test -- --no-cov
