name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Python Dependencies
        run: |
          pip install -r requirements/build-docs.txt
          pip install -r requirements/check-types.txt
          pip install -r requirements/check-style.txt
          pip install -e .
      - name: Check docs build
        run: |
          linkcheckMarkdown docs/ -v -r
          linkcheckMarkdown README.md -v -r
          linkcheckMarkdown CHANGELOG.md -v -r
          cd docs
          mkdocs build --strict
      - name: Check docs examples
        run: |
          mypy --show-error-codes docs/examples/python/
          ruff check docs/examples/python/
