name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Python Dependencies
        run: |
          pip3 --quiet install --upgrade hatch uv ruff
      - name: Check docs build
        run: |
          hatch run docs:build
          hatch run docs:linkcheck
      - name: Check docs examples
        run: |
          ruff check docs/examples/python/
